# seeds.py
from app import create_app
from models import db, Company, Job, JobCategory, ProxyPlan, SubscriptionPlan, User
from datetime import datetime, timedelta, timezone
import random

app = create_app()

with app.app_context():
    # Clear existing data (optional – comment out if you want to keep existing)
    db.drop_all()
    db.create_all()

    # ======================== COMPANIES ========================
    companies_data = [
        {'name': 'Acme Corp', 'description': 'A leading technology company.', 'website': 'https://acme.com', 'verified': True},
        {'name': 'EduRemote', 'description': 'Online education for everyone.', 'website': 'https://eduremote.com', 'verified': True},
        {'name': 'FinancePro', 'description': 'Financial services remotely delivered.', 'website': 'https://financepro.com', 'verified': False},
        {'name': 'HealthBridge', 'description': 'Telehealth and wellness services.', 'website': 'https://healthbridge.com', 'verified': True},
        {'name': 'WriteRight', 'description': 'Content writing and translation.', 'website': 'https://writeright.com', 'verified': True},
        {'name': 'Designify', 'description': 'Creative design studio.', 'website': 'https://designify.com', 'verified': True},
        {'name': 'MarketMint', 'description': 'Digital marketing agency.', 'website': 'https://marketmint.com', 'verified': False},
        {'name': 'CodeCrafters', 'description': 'Software development consultancy.', 'website': 'https://codecrafters.io', 'verified': True},
        {'name': 'LegalZoom', 'description': 'Online legal services.', 'website': 'https://legalzoom.com', 'verified': True},
        {'name': 'VirtualVA', 'description': 'Virtual assistant solutions.', 'website': 'https://virtualva.com', 'verified': False},
        {'name': 'CloudSphere', 'description': 'Cloud and DevOps services.', 'website': 'https://cloudsphere.com', 'verified': True},
        {'name': 'DataDriven', 'description': 'Data science and AI solutions.', 'website': 'https://datadriven.com', 'verified': True},
        {'name': 'TutorTree', 'description': 'Online tutoring platform.', 'website': 'https://tutortree.com', 'verified': True},
        {'name': 'SupportHub', 'description': 'Customer support outsourcing.', 'website': 'https://supporthub.com', 'verified': False},
        {'name': 'RealTrust', 'description': 'Remote real estate services.', 'website': 'https://realtrust.com', 'verified': True},
        {'name': 'ShopRemote', 'description': 'E‑commerce solutions.', 'website': 'https://shopremote.com', 'verified': True},
        {'name': 'EngiNet', 'description': 'Engineering and manufacturing.', 'website': 'https://enginet.com', 'verified': False},
        {'name': 'MediaVerse', 'description': 'Media and communications.', 'website': 'https://mediaverse.com', 'verified': True},
        {'name': 'ConsultPro', 'description': 'Business consulting firm.', 'website': 'https://consultpro.com', 'verified': True},
        {'name': 'LangBridge', 'description': 'Language services and translation.', 'website': 'https://langbridge.com', 'verified': True},
    ]

    companies = []
    for data in companies_data:
        company = Company(**data)
        db.session.add(company)
        companies.append(company)
    db.session.commit()

    # ======================== SUB-CATEGORIES ========================
    sub_categories = [
        'Python', 'React', 'JavaScript', 'UI/UX', 'Data Science', 'DevOps', 'AWS',
        'Marketing', 'SEO', 'Translation', 'English Tutoring', 'Math Tutoring',
        'French Tutoring', 'Accounting', 'Healthcare', 'Sales', 'Legal', 'HR',
        'Copywriting', 'Graphic Design'
    ]
    for name in sub_categories:
        slug = name.lower().replace(' ', '-')
        cat = JobCategory(name=name, slug=slug)
        db.session.add(cat)
    db.session.commit()

    # ======================== PROXY PLANS ========================
    proxy_plans_data = [
        {'name': 'Basic', 'description': 'Shared IP, US only. Good for light browsing.',
         'price': 45.0, 'duration': 'month', 'features': 'US IP, 5GB bandwidth, Shared IP',
         'popular': False, 'is_active': True},
        {'name': 'Residential', 'description': 'Residential IPs from multiple countries.',
         'price': 75.0, 'duration': 'month', 'features': '10+ countries, 20GB bandwidth, Residential IPs',
         'popular': True, 'is_active': True},
        {'name': 'Rotating', 'description': 'Auto‑rotating IPs every 10 minutes.',
         'price': 90.0, 'duration': 'month', 'features': 'Global IPs, 50GB bandwidth, Auto‑rotate',
         'popular': False, 'is_active': True},
        {'name': 'Dedicated', 'description': 'Private dedicated IP, full control.',
         'price': 120.0, 'duration': 'month', 'features': 'Dedicated IP, Unlimited bandwidth, 24/7 support',
         'popular': False, 'is_active': True},
        {'name': 'Premium', 'description': 'Top‑tier proxy with all features.',
         'price': 199.0, 'duration': 'month', 'features': 'Dedicated IP, Unlimited bandwidth, Priority support, All countries',
         'popular': False, 'is_active': True},
    ]
    for plan_data in proxy_plans_data:
        plan = ProxyPlan(**plan_data)
        db.session.add(plan)
    db.session.commit()

    # ======================== SUBSCRIPTION PLAN (CHAT) ========================
    chat_plan = SubscriptionPlan(
        name='Chat Unlimited',
        description='Unlock unlimited messages after 5 free replies. $20/month.',
        price=20.0,
        duration_days=30,
        message_limit=0,       # 0 = unlimited after payment
        is_active=True
    )
    db.session.add(chat_plan)
    db.session.commit()

    # ======================== ADMIN USER ========================
    admin = User(
        username='admin',
        email='admin@remotehub.com',
        full_name='RemoteHub Admin',
        is_admin=True
    )
    admin.set_password('admin123')
    db.session.add(admin)
    db.session.commit()

    # ======================== HELPERS ========================
    def days_ago(days):
        return datetime.now(timezone.utc) - timedelta(days=days)

    def get_company_id(idx):
        """Convert company list index to actual database id."""
        return companies[idx].id

    # ======================== ALL JOBS ========================
    all_jobs = {
        'Technology & Development': [
            {'title': 'Senior Python Developer', 'company': 0, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$120k-150k',
             'experience_level': 'Senior', 'skills_required': 'Python, Django, Flask, PostgreSQL',
             'description': 'Build scalable microservices with Python, FastAPI, and AWS. Join a remote-first team.',
             'posted_date': days_ago(2)},
            {'title': 'React Frontend Engineer', 'company': 7, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-70/hr',
             'experience_level': 'Mid-level', 'skills_required': 'React, TypeScript, Tailwind',
             'description': 'Create beautiful dashboards with React, Tailwind, and TypeScript.',
             'posted_date': days_ago(5)},
            {'title': 'Java Backend Developer', 'company': 1, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$100k-130k',
             'experience_level': 'Senior', 'skills_required': 'Java, Spring Boot, Microservices',
             'description': 'Design and implement robust backend systems for our e‑commerce platform.',
             'posted_date': days_ago(1)},
            {'title': 'Full Stack JavaScript Developer', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'experience_level': 'Mid-level', 'skills_required': 'Node.js, React, MongoDB',
             'description': 'Work on cutting-edge web applications using the MERN stack.',
             'posted_date': days_ago(3)},
            {'title': 'DevOps Engineer', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$130k-160k',
             'experience_level': 'Senior', 'skills_required': 'Docker, Kubernetes, AWS, CI/CD',
             'description': 'Manage and improve our cloud infrastructure and deployment pipelines.',
             'posted_date': days_ago(4)},
            {'title': 'Angular Developer', 'company': 7, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$40-60/hr',
             'experience_level': 'Mid-level', 'skills_required': 'Angular, RxJS, TypeScript',
             'description': 'Develop modern single‑page applications for our clients.',
             'posted_date': days_ago(6)},
            {'title': 'Vue.js Frontend Developer', 'company': 0, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$35-50/hr',
             'experience_level': 'Junior', 'skills_required': 'Vue.js, Vuex, JavaScript',
             'description': 'Assist in building user interfaces for our SaaS product.',
             'posted_date': days_ago(8)},
            {'title': 'PHP/Laravel Developer', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'experience_level': 'Mid-level', 'skills_required': 'PHP, Laravel, MySQL',
             'description': 'Maintain and extend our CMS and custom web applications.',
             'posted_date': days_ago(7)},
            {'title': 'Django Developer', 'company': 0, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$55-75/hr',
             'experience_level': 'Senior', 'skills_required': 'Django, Python, PostgreSQL',
             'description': 'Lead a small team building a Django‑based marketplace.',
             'posted_date': days_ago(2)},
            {'title': 'Flask API Developer', 'company': 7, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$45-65/hr',
             'experience_level': 'Mid-level', 'skills_required': 'Python, Flask, REST APIs',
             'description': 'Create lightweight RESTful APIs for mobile applications.',
             'posted_date': days_ago(9)},
            {'title': 'SQL Database Administrator', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$110k-140k',
             'experience_level': 'Senior', 'skills_required': 'SQL, PostgreSQL, Performance Tuning',
             'description': 'Optimize and manage large-scale relational databases.',
             'posted_date': days_ago(3)},
            {'title': 'MongoDB Developer', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$95k-125k',
             'experience_level': 'Mid-level', 'skills_required': 'MongoDB, Aggregation Framework',
             'description': 'Design NoSQL schemas for a real‑time analytics platform.',
             'posted_date': days_ago(4)},
            {'title': 'Docker/Kubernetes Specialist', 'company': 10, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$70-90/hr',
             'experience_level': 'Senior', 'skills_required': 'Docker, Kubernetes, Helm',
             'description': 'Architect container orchestration for microservices.',
             'posted_date': days_ago(5)},
            {'title': 'AWS Cloud Architect', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$150k-180k',
             'experience_level': 'Senior', 'skills_required': 'AWS, Terraform, CloudFormation',
             'description': 'Design and govern AWS cloud environments for our enterprise clients.',
             'posted_date': days_ago(1)},
            {'title': 'Azure DevOps Engineer', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$125k-155k',
             'experience_level': 'Senior', 'skills_required': 'Azure, Azure DevOps, CI/CD',
             'description': 'Implement CI/CD pipelines and Azure infrastructure.',
             'posted_date': days_ago(6)},
            {'title': 'Google Cloud Platform Engineer', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$130k-160k',
             'experience_level': 'Senior', 'skills_required': 'GCP, BigQuery, Kubernetes',
             'description': 'Manage GCP infrastructure and data services for a fast-growing startup.',
             'posted_date': days_ago(2)},
            {'title': 'Cybersecurity Analyst', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$115k-145k',
             'experience_level': 'Mid-level', 'skills_required': 'Penetration Testing, SIEM, Incident Response',
             'description': 'Protect our systems and data from cyber threats.',
             'posted_date': days_ago(3)},
            {'title': 'AI/Machine Learning Engineer', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$140k-170k',
             'experience_level': 'Senior', 'skills_required': 'Python, TensorFlow, PyTorch',
             'description': 'Develop and deploy machine learning models at scale.',
             'posted_date': days_ago(1)},
            {'title': 'Data Scientist', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$130k-160k',
             'experience_level': 'Mid-level', 'skills_required': 'Python, R, Machine Learning, Statistics',
             'description': 'Extract insights from complex datasets and build predictive models.',
             'posted_date': days_ago(7)},
            {'title': 'Junior Web Developer', 'company': 7, 'employment_type': 'Internship', 'location': 'Remote', 'salary': '$20-30/hr',
             'experience_level': 'Entry', 'skills_required': 'HTML, CSS, JavaScript, Git',
             'description': 'Kickstart your career building real web projects with our mentorship program.',
             'posted_date': days_ago(10)},
        ],
        'Design & Creative': [
            {'title': 'UI/UX Designer', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Design intuitive interfaces for our SaaS platform.', 'posted_date': days_ago(3)},
            {'title': 'Graphic Designer', 'company': 5, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Create marketing materials and social media graphics.', 'posted_date': days_ago(5)},
            {'title': 'Motion Graphics Designer', 'company': 5, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Produce engaging motion graphics for video content.', 'posted_date': days_ago(4)},
            {'title': 'Brand Identity Designer', 'company': 5, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Develop visual identity systems for startups and small businesses.', 'posted_date': days_ago(8)},
            {'title': 'Illustrator', 'company': 5, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Create custom illustrations for children\'s books and apps.', 'posted_date': days_ago(7)},
            {'title': '3D Designer', 'company': 5, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr',
             'description': 'Model and render 3D assets for e‑commerce and games.', 'posted_date': days_ago(6)},
            {'title': 'Art Director', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$100k-130k',
             'description': 'Lead our design team and define the visual style of our products.', 'posted_date': days_ago(2)},
            {'title': 'Web Designer', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Design and implement visually appealing websites.', 'posted_date': days_ago(9)},
            {'title': 'Product Designer', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$110k-140k',
             'description': 'Drive the end‑to‑end design process for our core product.', 'posted_date': days_ago(1)},
            {'title': 'Creative Strategist', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Develop creative concepts for digital ad campaigns.', 'posted_date': days_ago(5)},
            {'title': 'Packaging Designer', 'company': 5, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Design packaging for consumer products.', 'posted_date': days_ago(10)},
            {'title': 'Fashion Illustrator', 'company': 5, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Create fashion flats and illustrations for our clothing line.', 'posted_date': days_ago(11)},
            {'title': 'Game Designer', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Design engaging mobile games with a small remote team.', 'posted_date': days_ago(4)},
            {'title': 'Architectural Visualizer', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-55/hr',
             'description': 'Produce photorealistic renderings for architectural projects.', 'posted_date': days_ago(6)},
            {'title': 'Creative Writer', 'company': 4, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Write compelling copy for ads, video scripts, and brand stories.', 'posted_date': days_ago(8)},
        ],
        'Writing & Translation': [
            {'title': 'Content Writer', 'company': 4, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Write blog posts, articles, and website copy on a variety of topics.', 'posted_date': days_ago(5)},
            {'title': 'Copywriter', 'company': 4, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-80k',
             'description': 'Craft persuasive marketing copy for emails, landing pages, and ads.', 'posted_date': days_ago(3)},
            {'title': 'Technical Writer', 'company': 0, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-55/hr',
             'description': 'Document APIs and write user guides for software products.', 'posted_date': days_ago(7)},
            {'title': 'Translator (English to Spanish)', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Translate legal and business documents between English and Spanish.', 'posted_date': days_ago(4)},
            {'title': 'Proofreader', 'company': 4, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$18-25/hr',
             'description': 'Proofread manuscripts and articles for grammar and consistency.', 'posted_date': days_ago(6)},
            {'title': 'Transcriptionist', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$15-25/hr',
             'description': 'Transcribe audio recordings into written text.', 'posted_date': days_ago(2)},
            {'title': 'Localization Specialist', 'company': 19, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-90k',
             'description': 'Adapt content for different languages and cultures.', 'posted_date': days_ago(8)},
            {'title': 'Subtitler', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Create subtitles for videos and live streams.', 'posted_date': days_ago(9)},
            {'title': 'SEO Content Writer', 'company': 4, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-75k',
             'description': 'Write SEO‑optimized content to drive organic traffic.', 'posted_date': days_ago(1)},
            {'title': 'Grant Writer', 'company': 4, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-50/hr',
             'description': 'Prepare grant proposals for non‑profit organizations.', 'posted_date': days_ago(10)},
            {'title': 'Resume Writer', 'company': 4, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Help clients craft professional resumes and cover letters.', 'posted_date': days_ago(11)},
            {'title': 'Editor', 'company': 4, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$65k-85k',
             'description': 'Manage editorial content and mentor junior writers.', 'posted_date': days_ago(12)},
        ],
        'Marketing & Sales': [
            {'title': 'Digital Marketing Manager', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Plan and execute digital marketing campaigns across channels.', 'posted_date': days_ago(4)},
            {'title': 'SEO Specialist', 'company': 6, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Optimize websites to improve search engine rankings.', 'posted_date': days_ago(2)},
            {'title': 'Social Media Manager', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-80k',
             'description': 'Grow and engage our social media audiences.', 'posted_date': days_ago(3)},
            {'title': 'PPC Specialist', 'company': 6, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Manage Google Ads and Facebook Ads campaigns.', 'posted_date': days_ago(5)},
            {'title': 'Sales Representative', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k + commission',
             'description': 'Drive B2B sales for our SaaS product.', 'posted_date': days_ago(1)},
            {'title': 'Affiliate Manager', 'company': 6, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Recruit and manage affiliate partners.', 'posted_date': days_ago(7)},
            {'title': 'Email Marketing Specialist', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-75k',
             'description': 'Create and automate email marketing campaigns.', 'posted_date': days_ago(6)},
            {'title': 'Market Research Analyst', 'company': 6, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-40/hr',
             'description': 'Conduct market analysis and competitive research.', 'posted_date': days_ago(8)},
            {'title': 'Brand Manager', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Oversee brand strategy and positioning.', 'posted_date': days_ago(9)},
            {'title': 'E‑commerce Marketing', 'company': 16, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$65k-90k',
             'description': 'Drive traffic and sales for our Shopify store.', 'posted_date': days_ago(10)},
            {'title': 'Influencer Outreach Coordinator', 'company': 6, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Build relationships with influencers and manage collaborations.', 'posted_date': days_ago(11)},
            {'title': 'CRM Administrator', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Manage HubSpot / Salesforce and optimize sales processes.', 'posted_date': days_ago(12)},
        ],
        'Business & Finance': [
            {'title': 'Remote Accountant', 'company': 2, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-90k',
             'description': 'Manage financial records, prepare tax returns, and advise clients.', 'posted_date': days_ago(4)},
            {'title': 'Financial Analyst', 'company': 2, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Analyze financial data and build forecasting models.', 'posted_date': days_ago(3)},
            {'title': 'Bookkeeper', 'company': 2, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Maintain day‑to‑day financial transactions for small businesses.', 'posted_date': days_ago(6)},
            {'title': 'Tax Consultant', 'company': 2, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr',
             'description': 'Provide tax planning and filing services.', 'posted_date': days_ago(7)},
            {'title': 'Payroll Specialist', 'company': 2, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-70k',
             'description': 'Process payroll and ensure compliance.', 'posted_date': days_ago(2)},
            {'title': 'Business Consultant', 'company': 18, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-75/hr',
             'description': 'Advise startups on growth strategies.', 'posted_date': days_ago(5)},
            {'title': 'Project Manager', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Lead cross‑functional remote teams to deliver projects on time.', 'posted_date': days_ago(1)},
            {'title': 'Operations Manager', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$85k-115k',
             'description': 'Optimize remote work processes and tools.', 'posted_date': days_ago(4)},
            {'title': 'HR Generalist', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-80k',
             'description': 'Handle recruiting, onboarding, and employee relations.', 'posted_date': days_ago(8)},
            {'title': 'Recruiter', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-75k + commission',
             'description': 'Source and hire top talent for our global clients.', 'posted_date': days_ago(3)},
            {'title': 'Executive Assistant', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k',
             'description': 'Support C‑level executives with scheduling and communications.', 'posted_date': days_ago(9)},
            {'title': 'Data Entry Specialist', 'company': 2, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$12-18/hr',
             'description': 'Accurately enter data into spreadsheets and databases.', 'posted_date': days_ago(10)},
        ],
        'Virtual Assistance': [
            {'title': 'Virtual Assistant', 'company': 9, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$15-25/hr',
             'description': 'Provide administrative support, manage emails, and schedule appointments.', 'posted_date': days_ago(3)},
            {'title': 'Social Media Virtual Assistant', 'company': 9, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$18-28/hr',
             'description': 'Manage social media accounts and create content calendars.', 'posted_date': days_ago(4)},
            {'title': 'Real Estate Virtual Assistant', 'company': 14, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Assist real estate agents with listings, CRM, and client communication.', 'posted_date': days_ago(5)},
            {'title': 'E‑commerce VA', 'company': 9, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$16-26/hr',
             'description': 'Handle product listings, customer emails, and order fulfillment.', 'posted_date': days_ago(2)},
            {'title': 'Tech VA', 'company': 9, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Support tech startup founders with research and tool setup.', 'posted_date': days_ago(6)},
            {'title': 'Personal Assistant', 'company': 9, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$40k-55k',
             'description': 'Manage personal and professional tasks for busy executives.', 'posted_date': days_ago(7)},
            {'title': 'Bookkeeping VA', 'company': 9, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$18-25/hr',
             'description': 'Handle invoice and expense tracking for multiple clients.', 'posted_date': days_ago(8)},
            {'title': 'Customer Service VA', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$15-22/hr',
             'description': 'Respond to customer inquiries via email and chat.', 'posted_date': days_ago(1)},
            {'title': 'Research VA', 'company': 9, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Conduct internet research and compile reports.', 'posted_date': days_ago(9)},
            {'title': 'Travel Coordinator VA', 'company': 9, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$18-28/hr',
             'description': 'Book flights, hotels, and manage travel itineraries.', 'posted_date': days_ago(10)},
        ],
        'Customer Support': [
            {'title': 'Customer Support Representative', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$18-25/hr',
             'description': 'Answer customer tickets via Zendesk.', 'posted_date': days_ago(2)},
            {'title': 'Technical Support Specialist', 'company': 0, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$22-30/hr',
             'description': 'Troubleshoot technical issues for our software users.', 'posted_date': days_ago(3)},
            {'title': 'Live Chat Agent', 'company': 13, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$15-20/hr',
             'description': 'Provide instant support via live chat on our website.', 'posted_date': days_ago(4)},
            {'title': 'Call Center Agent', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$16-22/hr',
             'description': 'Handle inbound calls and resolve customer issues.', 'posted_date': days_ago(5)},
            {'title': 'Customer Success Manager', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-90k',
             'description': 'Ensure customers achieve their desired outcomes.', 'posted_date': days_ago(1)},
            {'title': 'Complaints Specialist', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$19-26/hr',
             'description': 'Resolve escalated customer complaints and maintain satisfaction.', 'posted_date': days_ago(6)},
            {'title': 'Bilingual Support (English/French)', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$20-28/hr',
             'description': 'Assist French‑speaking customers via phone and email.', 'posted_date': days_ago(7)},
            {'title': 'Support Team Lead', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-100k',
             'description': 'Manage a remote support team and improve processes.', 'posted_date': days_ago(8)},
            {'title': 'Knowledge Base Writer', 'company': 13, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Create help articles and FAQs.', 'posted_date': days_ago(9)},
            {'title': 'IT Help Desk', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$20-28/hr',
             'description': 'Support internal employees with IT issues.', 'posted_date': days_ago(10)},
        ],
        'Education & Tutoring': [
            {'title': 'Online English Tutor', 'company': 12, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Teach English to students worldwide. No experience required.', 'posted_date': days_ago(2)},
            {'title': 'Mathematics Tutor', 'company': 12, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Tutor high school and college math online.', 'posted_date': days_ago(3)},
            {'title': 'French Tutor', 'company': 12, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$22-35/hr',
             'description': 'Teach French language to beginners and intermediate learners.', 'posted_date': days_ago(4)},
            {'title': 'Science Tutor (Physics)', 'company': 12, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-45/hr',
             'description': 'Help students master physics concepts.', 'posted_date': days_ago(5)},
            {'title': 'Coding Instructor', 'company': 7, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-50/hr',
             'description': 'Teach Python and JavaScript to kids and adults.', 'posted_date': days_ago(6)},
            {'title': 'Music Teacher', 'company': 12, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Give online piano or guitar lessons.', 'posted_date': days_ago(7)},
            {'title': 'Test Prep Coach', 'company': 12, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Prepare students for SAT, ACT, or GRE exams.', 'posted_date': days_ago(8)},
            {'title': 'Curriculum Developer', 'company': 12, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Design online courses and learning materials.', 'posted_date': days_ago(9)},
            {'title': 'Academic Advisor', 'company': 12, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k',
             'description': 'Guide students in their academic and career choices.', 'posted_date': days_ago(10)},
            {'title': 'Special Education Tutor', 'company': 12, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Work with students who have learning differences.', 'posted_date': days_ago(11)},
            {'title': 'English Literature Tutor', 'company': 12, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Help students with essay writing and literature analysis.', 'posted_date': days_ago(12)},
            {'title': 'Business English Coach', 'company': 12, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Coach professionals in business communication skills.', 'posted_date': days_ago(13)},
        ],
        'Healthcare & Wellness': [
            {'title': 'Telehealth Nurse', 'company': 3, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Provide remote patient consultations and triage.', 'posted_date': days_ago(2)},
            {'title': 'Medical Transcriptionist', 'company': 3, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Transcribe medical dictations for clinics.', 'posted_date': days_ago(3)},
            {'title': 'Health Coach', 'company': 3, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Coach clients on nutrition and lifestyle changes.', 'posted_date': days_ago(4)},
            {'title': 'Mental Health Counselor', 'company': 3, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-85k',
             'description': 'Provide online therapy sessions.', 'posted_date': days_ago(5)},
            {'title': 'Wellness Content Writer', 'company': 4, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Write articles on health, fitness, and mindfulness.', 'posted_date': days_ago(6)},
            {'title': 'Fitness Instructor', 'company': 3, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Lead virtual yoga or HIIT classes.', 'posted_date': days_ago(7)},
            {'title': 'Nutritionist', 'company': 3, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Create personalized meal plans for clients.', 'posted_date': days_ago(8)},
            {'title': 'Medical Biller', 'company': 3, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$40k-55k',
             'description': 'Process medical claims and insurance billing.', 'posted_date': days_ago(9)},
            {'title': 'Clinical Data Analyst', 'company': 3, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Analyze clinical trial data.', 'posted_date': days_ago(10)},
            {'title': 'Telemedicine Coordinator', 'company': 3, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$45k-60k',
             'description': 'Schedule virtual appointments and manage patient flow.', 'posted_date': days_ago(11)},
        ],
        'Legal Services': [
            {'title': 'Remote Paralegal', 'company': 8, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k',
             'description': 'Assist attorneys with legal research and document preparation.', 'posted_date': days_ago(2)},
            {'title': 'Contract Attorney', 'company': 8, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$60-90/hr',
             'description': 'Review and draft contracts for businesses.', 'posted_date': days_ago(3)},
            {'title': 'Legal Transcriptionist', 'company': 8, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Transcribe court proceedings and depositions.', 'posted_date': days_ago(4)},
            {'title': 'Compliance Officer', 'company': 8, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Ensure company policies meet legal requirements.', 'posted_date': days_ago(5)},
            {'title': 'Intellectual Property Lawyer', 'company': 8, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$70-100/hr',
             'description': 'File patents and trademarks for startups.', 'posted_date': days_ago(6)},
            {'title': 'Immigration Consultant', 'company': 8, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr',
             'description': 'Assist clients with visa applications.', 'posted_date': days_ago(7)},
            {'title': 'Legal Researcher', 'company': 8, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Conduct in‑depth legal research for cases.', 'posted_date': days_ago(8)},
            {'title': 'Corporate Secretary', 'company': 8, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Maintain corporate records and board minutes.', 'posted_date': days_ago(9)},
            {'title': 'Freelance Mediator', 'company': 8, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$50-75/hr',
             'description': 'Mediate disputes between parties online.', 'posted_date': days_ago(10)},
            {'title': 'Data Privacy Consultant', 'company': 8, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$60-85/hr',
             'description': 'Advise on GDPR and CCPA compliance.', 'posted_date': days_ago(11)},
        ],
        'Media & Communications': [
            {'title': 'Journalist', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-80k',
             'description': 'Investigate and write news stories for our digital publication.', 'posted_date': days_ago(2)},
            {'title': 'Public Relations Specialist', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-85k',
             'description': 'Manage media relations and press releases.', 'posted_date': days_ago(3)},
            {'title': 'Podcast Producer', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-50/hr',
             'description': 'Edit and produce weekly podcast episodes.', 'posted_date': days_ago(4)},
            {'title': 'Video Editor', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-45/hr',
             'description': 'Edit video content for YouTube and social media.', 'posted_date': days_ago(5)},
            {'title': 'Social Media Content Creator', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$45k-65k',
             'description': 'Create engaging short‑form videos and posts.', 'posted_date': days_ago(6)},
            {'title': 'Photographer', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-40/hr',
             'description': 'License stock photos and take custom shoots.', 'posted_date': days_ago(7)},
            {'title': 'Voice Over Artist', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-40/hr',
             'description': 'Record voice overs for commercials and audiobooks.', 'posted_date': days_ago(8)},
            {'title': 'Copy Editor', 'company': 17, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$25-35/hr',
             'description': 'Proofread and edit articles before publication.', 'posted_date': days_ago(9)},
            {'title': 'Broadcast Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Manage streaming infrastructure for live events.', 'posted_date': days_ago(10)},
            {'title': 'Digital Media Planner', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$65k-85k',
             'description': 'Plan and buy digital media placements.', 'posted_date': days_ago(11)},
        ],
        'Real Estate': [
            {'title': 'Remote Real Estate Agent', 'company': 14, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$50k-80k commission',
             'description': 'Assist clients in buying and selling homes virtually.', 'posted_date': days_ago(2)},
            {'title': 'Property Manager', 'company': 14, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$55k-75k',
             'description': 'Manage a portfolio of rental properties remotely.', 'posted_date': days_ago(3)},
            {'title': 'Mortgage Broker', 'company': 14, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr + commission',
             'description': 'Help clients secure home financing online.', 'posted_date': days_ago(4)},
            {'title': 'Real Estate Transaction Coordinator', 'company': 14, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$40k-55k',
             'description': 'Manage paperwork and deadlines for real estate deals.', 'posted_date': days_ago(5)},
            {'title': 'Leasing Consultant', 'company': 14, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$35k-50k',
             'description': 'Conduct virtual property tours and process applications.', 'posted_date': days_ago(6)},
            {'title': 'Real Estate Photographer', 'company': 14, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Edit and deliver high‑quality property photos.', 'posted_date': days_ago(7)},
            {'title': 'Title Examiner', 'company': 14, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Research property titles and resolve issues.', 'posted_date': days_ago(8)},
            {'title': 'Real Estate Appraiser', 'company': 14, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Provide remote desktop appraisals for lenders.', 'posted_date': days_ago(9)},
            {'title': 'Real Estate Virtual Tour Creator', 'company': 14, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-40/hr',
             'description': 'Create 3D virtual tours using Matterport.', 'posted_date': days_ago(10)},
            {'title': 'Commercial Real Estate Analyst', 'company': 14, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Analyze commercial property investments.', 'posted_date': days_ago(11)},
        ],
        'E-commerce': [
            {'title': 'E‑commerce Manager', 'company': 16, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Oversee online store operations and growth strategy.', 'posted_date': days_ago(2)},
            {'title': 'Shopify Developer', 'company': 16, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr',
             'description': 'Customize Shopify themes and apps.', 'posted_date': days_ago(3)},
            {'title': 'Amazon Seller Specialist', 'company': 16, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-45/hr',
             'description': 'Optimize product listings and manage Amazon PPC.', 'posted_date': days_ago(4)},
            {'title': 'Product Lister', 'company': 16, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$15-22/hr',
             'description': 'Create and upload product descriptions and images.', 'posted_date': days_ago(5)},
            {'title': 'Supply Chain Coordinator', 'company': 16, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k',
             'description': 'Coordinate with suppliers and manage inventory.', 'posted_date': days_ago(6)},
            {'title': 'E‑commerce Customer Service', 'company': 16, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$16-23/hr',
             'description': 'Handle order inquiries and returns.', 'posted_date': days_ago(7)},
            {'title': 'eBay/Shopify Lister', 'company': 16, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$18-28/hr',
             'description': 'List products across multiple marketplaces.', 'posted_date': days_ago(8)},
            {'title': 'Dropshipping Manager', 'company': 16, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$20-30/hr',
             'description': 'Set up and manage dropshipping operations.', 'posted_date': days_ago(9)},
            {'title': 'E‑commerce Analyst', 'company': 16, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$65k-85k',
             'description': 'Analyze sales data and customer behavior.', 'posted_date': days_ago(10)},
            {'title': 'Packaging Designer (E‑commerce)', 'company': 5, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Design packaging for direct‑to‑consumer brands.', 'posted_date': days_ago(11)},
        ],
        'Engineering': [
            {'title': 'Mechanical Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Design mechanical components using CAD software.', 'posted_date': days_ago(2)},
            {'title': 'Civil Engineer', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$45-65/hr',
             'description': 'Plan and oversee infrastructure projects remotely.', 'posted_date': days_ago(3)},
            {'title': 'Electrical Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$85k-115k',
             'description': 'Design circuit boards and electrical systems.', 'posted_date': days_ago(4)},
            {'title': 'Software Engineer (Embedded)', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$100k-130k',
             'description': 'Develop firmware for IoT devices.', 'posted_date': days_ago(5)},
            {'title': 'QA Engineer', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Manual and automated testing of web applications.', 'posted_date': days_ago(6)},
            {'title': 'Product Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Bring new consumer products from concept to production.', 'posted_date': days_ago(7)},
            {'title': 'Structural Engineer', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-70/hr',
             'description': 'Analyze and design building structures.', 'posted_date': days_ago(8)},
            {'title': 'Robotics Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$100k-140k',
             'description': 'Program and simulate robotic systems.', 'posted_date': days_ago(9)},
            {'title': 'Chemical Engineer', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$55-75/hr',
             'description': 'Optimize chemical processes for manufacturing.', 'posted_date': days_ago(10)},
            {'title': 'Project Engineer', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$85k-110k',
             'description': 'Coordinate engineering projects from start to finish.', 'posted_date': days_ago(11)},
        ],
        'Research & Analysis': [
            {'title': 'Market Research Analyst', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-85k',
             'description': 'Gather and interpret market data to inform business strategies.', 'posted_date': days_ago(2)},
            {'title': 'Business Analyst', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$75k-100k',
             'description': 'Analyze business processes and recommend improvements.', 'posted_date': days_ago(3)},
            {'title': 'Data Analyst', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-110k',
             'description': 'Analyze complex datasets and deliver actionable insights.', 'posted_date': days_ago(4)},
            {'title': 'Policy Researcher', 'company': 8, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Research public policy and write briefs.', 'posted_date': days_ago(5)},
            {'title': 'Scientific Researcher', 'company': 3, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$70k-95k',
             'description': 'Conduct literature reviews and data analysis for clinical studies.', 'posted_date': days_ago(6)},
            {'title': 'Competitive Intelligence Analyst', 'company': 6, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-105k',
             'description': 'Monitor competitors and industry trends.', 'posted_date': days_ago(7)},
            {'title': 'Survey Designer', 'company': 6, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Create and analyze surveys for market research.', 'posted_date': days_ago(8)},
            {'title': 'Financial Researcher', 'company': 2, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$35-50/hr',
             'description': 'Analyze stocks and write investment reports.', 'posted_date': days_ago(9)},
            {'title': 'UX Researcher', 'company': 5, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$90k-120k',
             'description': 'Conduct user interviews and usability testing.', 'posted_date': days_ago(10)},
            {'title': 'Operations Analyst', 'company': 18, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$65k-85k',
             'description': 'Improve operational efficiency through data analysis.', 'posted_date': days_ago(11)},
        ],
        'AI & Automation': [
            {'title': 'AI Research Scientist', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$150k-200k',
             'description': 'Advance the state of the art in machine learning.', 'posted_date': days_ago(2)},
            {'title': 'NLP Engineer', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$130k-160k',
             'description': 'Build natural language processing models for chatbots.', 'posted_date': days_ago(3)},
            {'title': 'Computer Vision Engineer', 'company': 11, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$140k-170k',
             'description': 'Develop image recognition and processing algorithms.', 'posted_date': days_ago(4)},
            {'title': 'MLOps Engineer', 'company': 10, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$120k-150k',
             'description': 'Deploy and monitor machine learning models in production.', 'posted_date': days_ago(5)},
            {'title': 'RPA Developer', 'company': 10, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-70/hr',
             'description': 'Automate business processes using UiPath.', 'posted_date': days_ago(6)},
            {'title': 'AI Product Manager', 'company': 0, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$140k-180k',
             'description': 'Define the roadmap for AI‑powered features.', 'posted_date': days_ago(7)},
            {'title': 'Chatbot Developer', 'company': 7, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$35-55/hr',
             'description': 'Build conversational AI chatbots for websites.', 'posted_date': days_ago(8)},
            {'title': 'Data Labeling Specialist', 'company': 11, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$15-22/hr',
             'description': 'Annotate images and text for machine learning datasets.', 'posted_date': days_ago(9)},
            {'title': 'AI Ethics Consultant', 'company': 8, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$60-85/hr',
             'description': 'Advise on responsible AI practices.', 'posted_date': days_ago(10)},
            {'title': 'Automation Tester', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$75k-95k',
             'description': 'Develop automated test scripts for AI/ML pipelines.', 'posted_date': days_ago(11)},
        ],
        'Consulting & Coaching': [
            {'title': 'Business Coach', 'company': 18, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$50-100/hr',
             'description': 'Coach entrepreneurs on business growth strategies.', 'posted_date': days_ago(2)},
            {'title': 'Career Coach', 'company': 18, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$40-80/hr',
             'description': 'Help professionals transition into remote careers.', 'posted_date': days_ago(3)},
            {'title': 'Life Coach', 'company': 18, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$45-85/hr',
             'description': 'Guide clients toward personal and professional goals.', 'posted_date': days_ago(4)},
            {'title': 'Management Consultant', 'company': 18, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$70-120/hr',
             'description': 'Advise Fortune 500 companies on organizational change.', 'posted_date': days_ago(5)},
            {'title': 'IT Consultant', 'company': 10, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$60-90/hr',
             'description': 'Assess and improve clients\' technology infrastructure.', 'posted_date': days_ago(6)},
            {'title': 'Marketing Consultant', 'company': 6, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-80/hr',
             'description': 'Develop go‑to‑market strategies for startups.', 'posted_date': days_ago(7)},
            {'title': 'Financial Advisor', 'company': 2, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$60-100/hr',
             'description': 'Provide personal financial planning sessions via video.', 'posted_date': days_ago(8)},
            {'title': 'Leadership Coach', 'company': 18, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$75-125/hr',
             'description': 'Coach executives on leadership and communication.', 'posted_date': days_ago(9)},
            {'title': 'Sales Coach', 'company': 6, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$50-80/hr',
             'description': 'Train sales teams to improve their closing rates.', 'posted_date': days_ago(10)},
            {'title': 'Wellness Consultant', 'company': 3, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$40-70/hr',
             'description': 'Design workplace wellness programs.', 'posted_date': days_ago(11)},
        ],
        'Language Services': [
            {'title': 'Translator (French)', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Translate technical documents from French to English.', 'posted_date': days_ago(2)},
            {'title': 'Interpreter', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-50/hr',
             'description': 'Provide live interpretation for business meetings.', 'posted_date': days_ago(3)},
            {'title': 'Localization Tester', 'company': 19, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Test software UI for language accuracy and cultural appropriateness.', 'posted_date': days_ago(4)},
            {'title': 'Voice Over Talent', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-45/hr',
             'description': 'Record voice overs in multiple languages.', 'posted_date': days_ago(5)},
            {'title': 'Language Instructor', 'company': 12, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$20-35/hr',
             'description': 'Teach languages to corporate clients.', 'posted_date': days_ago(6)},
            {'title': 'Transcreation Specialist', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-45/hr',
             'description': 'Adapt marketing content for global audiences.', 'posted_date': days_ago(7)},
            {'title': 'Sign Language Interpreter', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$35-55/hr',
             'description': 'Provide remote ASL interpretation.', 'posted_date': days_ago(8)},
            {'title': 'Dubbing Editor', 'company': 19, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Sync audio tracks for dubbed content.', 'posted_date': days_ago(9)},
            {'title': 'Language Data Annotator', 'company': 19, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$15-25/hr',
             'description': 'Annotate text for NLP projects.', 'posted_date': days_ago(10)},
            {'title': 'Bilingual Customer Support', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$18-28/hr',
             'description': 'Provide support in English and German.', 'posted_date': days_ago(11)},
        ],
        'Entertainment & Media': [
            {'title': 'Music Producer', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-60/hr',
             'description': 'Produce and mix tracks for independent artists.', 'posted_date': days_ago(2)},
            {'title': 'Game Developer', 'company': 7, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$80k-120k',
             'description': 'Develop games using Unity or Unreal Engine.', 'posted_date': days_ago(3)},
            {'title': 'Screenwriter', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-70/hr',
             'description': 'Write scripts for web series and films.', 'posted_date': days_ago(4)},
            {'title': 'Animator', 'company': 5, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$25-50/hr',
             'description': 'Create 2D/3D animations for entertainment projects.', 'posted_date': days_ago(5)},
            {'title': 'Social Media Influencer', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': 'Variable',
             'description': 'Create sponsored content for brands.', 'posted_date': days_ago(6)},
            {'title': 'Talent Agent', 'company': 17, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$60k-90k + commission',
             'description': 'Represent and book gigs for remote artists.', 'posted_date': days_ago(7)},
            {'title': 'Event Planner', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-45/hr',
             'description': 'Organize virtual events and conferences.', 'posted_date': days_ago(8)},
            {'title': 'Sound Designer', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$30-50/hr',
             'description': 'Create sound effects for games and films.', 'posted_date': days_ago(9)},
            {'title': 'Casting Director', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$40-60/hr',
             'description': 'Cast actors for remote commercials.', 'posted_date': days_ago(10)},
            {'title': 'Film Editor', 'company': 17, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$35-60/hr',
             'description': 'Edit feature films and documentaries.', 'posted_date': days_ago(11)},
        ],
        'General Remote Jobs': [
            {'title': 'Data Entry Clerk', 'company': 0, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$12-18/hr',
             'description': 'Enter data into spreadsheets and databases.', 'posted_date': days_ago(2)},
            {'title': 'Online Community Manager', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$50k-70k',
             'description': 'Manage and moderate online communities and forums.', 'posted_date': days_ago(3)},
            {'title': 'Transcriptionist', 'company': 19, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$15-25/hr',
             'description': 'Transcribe audio to text accurately.', 'posted_date': days_ago(4)},
            {'title': 'Virtual Event Host', 'company': 17, 'employment_type': 'Contract', 'location': 'Remote', 'salary': '$25-40/hr',
             'description': 'Host webinars and live streams.', 'posted_date': days_ago(5)},
            {'title': 'Mystery Shopper', 'company': 6, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$10-20/hr',
             'description': 'Evaluate customer service by making test purchases.', 'posted_date': days_ago(6)},
            {'title': 'Remote Administrative Assistant', 'company': 9, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$35k-50k',
             'description': 'Perform clerical and administrative tasks for a remote team.', 'posted_date': days_ago(7)},
            {'title': 'Call Center Representative', 'company': 13, 'employment_type': 'Full-time', 'location': 'Remote', 'salary': '$14-20/hr',
             'description': 'Make outbound calls for surveys or sales.', 'posted_date': days_ago(8)},
            {'title': 'Freelance Writer', 'company': 4, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$20-40/hr',
             'description': 'Write articles on any topic for various clients.', 'posted_date': days_ago(9)},
            {'title': 'Remote Proofreader', 'company': 4, 'employment_type': 'Part-time', 'location': 'Remote', 'salary': '$18-25/hr',
             'description': 'Proofread documents and fix errors.', 'posted_date': days_ago(10)},
            {'title': 'Online Tutor (General)', 'company': 12, 'employment_type': 'Freelance', 'location': 'Remote', 'salary': '$15-30/hr',
             'description': 'Tutor students in various subjects online.', 'posted_date': days_ago(11)},
        ],
    }

    # Insert all jobs
    for category, job_list in all_jobs.items():
        for job_data in job_list:
            job_data['company_id'] = get_company_id(job_data.pop('company'))
            job_data['parent_category'] = category
            job_data.setdefault('posted_date', days_ago(random.randint(1, 15)))
            job_data.setdefault('employment_type', 'Full-time')
            job_data.setdefault('location', 'Remote')
            job_data.setdefault('salary', '$50k-70k')
            job = Job(**job_data)
            db.session.add(job)

    db.session.commit()
    print(f"Seeding complete! {len(companies)} companies, many jobs across 20 categories, 5 proxy plans, 1 chat subscription plan, and an admin user.")